### ISSUE TITLE
Debuggers (DDT, SID/ZSID and Z8E) not working

### ISSUE THREAD

**Issue by weerd01** [davidgiven/cpmish#36]
Hi,

We are trying to get debuggers to work. Both DDT and SID/ZSID crash the machine hard. Z8E (i don't know this application, really) also fails. I try to learn about CP/M, and the use of debuggers is a big part of the journey. Thanks!

Dennis

**Comment by davidgiven** [comment]
Yes, indeed.

This turns out to be because the NC200 uses im 1 mode for interrupts, which are all vectored through rst 0x38. This is the one used by default by most debuggers. So, the debugger installs the trap handler and suddenly every interrupt causes a breakpoint, then bad things happen.

To use DDT or SID you'll need to patch them --- this was common so instructions should be supplied. I've also preconfigured Z8E so it should work out of the box.
